package Tests;

public class QUERY_CONSTANTS {
	
	
	public static final String[] directors = {
			"Adam Elliot",
			"Adrian Lyne",
			"Akira Kurosawa",
			"Alejandro González Iñárritu",
			"Alfonso Cuarón",
			"Alfred Hitchcock",
			"Andrei Tarkovsky",
			"Andrew Adamson",
			"Andrew Davis",
			"Andrew Stanton",
			"Andy Tennant",
			"Andy Wachowski",
			"Ang Lee",
			"Anne Fletcher",
			"Asghar Farhadi",
			"Barry Levinson",
			"Barry Sonnenfeld",
			"Betty Thomas",
			"Bibo Bergeron",
			"Bill Condon",
			"Billy Wilder",
			"Bobby Farrelly",
			"Brad Bird",
			"Brett Ratner",
			"Brian De Palma",
			"Bryan Singer",
			"Cameron Crowe",
			"Carlos Saldanha",
			"Carol Reed",
			"Catherine Hardwicke",
			"Chan-wook Park",
			"Charles Chaplin",
			"Charles Laughton",
			"Chris Buck",
			"Chris Columbus",
			"Chris Miller",
			"Chris Renaud",
			"Chris Wedge",
			"Chris Weitz",
			"Christopher Nolan",
			"Clint Eastwood",
			"Clyde Bruckman",
			"Clyde Geronimi",
			"Curtis Hanson",
			"Danny Boyle",
			"Dan Scanlon",
			"Darren Aronofsky",
			"David Fincher",
			"David Lean",
			"David Lynch",
			"David Silverman",
			"David Slade",
			"David Yates",
			"Dean DeBlois",
			"Denis Villeneuve",
			"Dennis Dugan",
			"Ethan Coen",
			"Eric Darnell",
			"Federico Fellini",
			"Fernando Meirelles",
			"Florian Henckel von Donnersmarck",
			"Francis Ford Coppola",
			"Francis Lawrence",
			"François Truffaut",
			"Frank Capra",
			"Frank Coraci",
			"Frank Darabont",
			"Frank Miller",
			"Franklin J. Schaffner",
			"Fritz Lang",
			"Gabriele Muccino",
			"Garry Marshall",
			"Gary Ross",
			"Gary Trousdale",
			"Gavin Hood",
			"Gavin O'Connor",
			"George Lucas",
			"George Miller",
			"George P. Cosmatos",
			"George Roy Hill",
			"Giuseppe Tornatore",
			"Gore Verbinski",
			"Guillermo del Toro",
			"Guy Ritchie",
			"Gus Van Sant",
			"Harald Zwart",
			"Harold Ramis",
			"Hayao Miyazaki",
			"Henri-Georges Clouzot",
			"Howard Hawks",
			"Ingmar Bergman",
			"Irvin Kershner",
			"Isao Takahata",
			"Ivan Reitman",
			"J.J. Abrams",
			"James Cameron",
			"James McTeigue",
			"Jan de Bont",
			"Jay Roach",
			"Jennifer Yuh",
			"Jerry Zucker",
			"Jim Sheridan",
			"Jimmy Hayward",
			"Joel Schumacher",
			"Joel Coen",
			"Joe Johnston",
			"John Carpenter",
			"John Ford",
			"John Frankenheimer",
			"John G. Avildsen",
			"John Huston",
			"John Lee Hancock",
			"John Lasseter",
			"John McTiernan",
			"John Sturges",
			"Jonathan Demme",
			"Jonathan Mostow",
			"Jon Favreau",
			"Jon Turteltaub",
			"Joseph Kosinski",
			"Joseph L. Mankiewicz",
			"Joon-ho Bong",
			"Joss Whedon",
			"Juan José Campanella",
			"Julian Schnabel",
			"Justin Lin",
			"Keenen Ivory Wayans",
			"Kenneth Branagh",
			"Kevin Costner",
			"Kevin Reynolds",
			"Kirk De Micco",
			"Krzysztof Kieslowski",
			"Lee Tamahori",
			"Lee Unkrich",
			"Leonard Nimoy",
			"Lewis Milestone",
			"Luc Besson",
			"Louis Leterrier",
			"Marc Forster",
			"Marc Webb",
			"Mark Andrews",
			"Mark Osborne",
			"Martin Brest",
			"Martin Campbell",
			"Martin Scorsese",
			"Mathieu Kassovitz",
			"M. Night Shyamalan",
			"Mel Gibson",
			"Michael Bay",
			"Michael Cimino",
			"Michael Curtiz",
			"Michael Mann",
			"Michael Patrick King",
			"Michel Gondry",
			"Michel Hazanavicius",
			"Mike Mitchell",
			"Mike Newell",
			"Milos Forman",
			"Nancy Meyers",
			"Nathan Greno",
			"Neill Blomkamp",
			"Oliver Hirschbiegel",
			"Oliver Stone",
			"Olivier Nakache",
			"Orson Welles",
			"Otto Preminger",
			"Paul Feig",
			"Paul Greengrass",
			"Paul Thomas Anderson",
			"Peter Berg",
			"Peter Faiman",
			"Peter Jackson",
			"Peter Segal",
			"Peter Weir",
			"Pierre Coffin",
			"Quentin Tarantino",
			"Raja Gosnell",
			"Randal Kleiser",
			"Richard Attenborough",
			"Richard Kelly",
			"Richard Linklater",
			"Richard Marquand",
			"Robert Mulligan",
			"Robert Rossen",
			"Robert Wise",
			"Robert Zemeckis",
			"Rob Letterman",
			"Rob Marshall",
			"Rob Reiner",
			"Roland Emmerich",
			"Roman Polanski"
			};

	
	
	final static String [] DIRECTOR_FREQ_NAME = {"Steven Spielberg","Alfred Hitchcock","Stanley Kubrick","Robert Zemeckis","Christopher Nolan","Martin Scorsese","Billy Wilder","Ron Howard","John Lasseter","Sergio Leone","Tim Burton","James Cameron","Michael Bay","Charles Chaplin","Quentin Tarantino","Chris Columbus","Hayao Miyazaki","Akira Kurosawa","Peter Jackson","George Lucas","Ridley Scott","Jay Roach","Ingmar Bergman","Clint Eastwood","David Yates","Guy Ritchie","Sam Raimi","Bryan Singer","Sidney Lumet","Roland Emmerich","Wolfgang Petersen","Francis Ford Coppola","William Wyler","Roman Polanski","Jon Favreau","Justin Lin","Stephen Sommers","Frank Capra","Eric Darnell","Barry Sonnenfeld","Brad Bird","Gore Verbinski","Andrew Adamson","Zack Snyder","Federico Fellini","Elia Kazan","Joseph L. Mankiewicz","Milos Forman","Sam Mendes","Richard Linklater","Tony Scott","Dennis Dugan","Darren Aronofsky","Mel Gibson","Paul Feig","Howard Hawks","Tom Shadyac","George Roy Hill","Joe Johnston","Rob Marshall","Orson Welles","Pierre Coffin","Joel Coen","David Fincher","Andrew Stanton","Victor Fleming","Alfonso Cuarón","Carlos Saldanha","David Lean","Tom Hooper","Fritz Lang","Paul Thomas Anderson","Brian De Palma","Pete Docter","Terry Gilliam","Jon Turteltaub","Shawn Levy","Ethan Coen","Garry Marshall","Chris Miller","Marc Forster","Brett Ratner","M. Night Shyamalan","Danny Boyle","Rob Reiner","J.J. Abrams","Paul Greengrass","Sydney Pollack","Mike Nichols","John Ford","Frank Darabont","Todd Phillips","John Huston","Andy Wachowski","Bill Condon","Clyde Geronimi","Rajkumar Hirani","Leonard Nimoy","Asghar Farhadi","Ron Clements","Lewis Milestone","Tim Hill","Betty Thomas","Tony Kaye","Alejandro González Iñárritu","Jean-Pierre Jeunet","Otto Preminger","Woody Allen","Joel Schumacher","Gary Trousdale","Martin Brest","Vittorio De Sica","Mark Andrews","Michael Curtiz","Martin Campbell","Giuseppe Tornatore","Fernando Meirelles","Louis Leterrier","Stuart Rosenberg","Peter Faiman","Kevin Costner","Henri-Georges Clouzot","Lee Tamahori","John McTiernan","Neill Blomkamp","Richard Kelly","Oliver Hirschbiegel","Michel Gondry","Tim Story","Adrian Lyne","Richard Attenborough","Jerry Zucker","Ivan Reitman","Gus Van Sant","Isao Takahata","Randal Kleiser","Harold Ramis","Peter Berg","George Miller","Mike Newell","Michael Mann","Fred Zinnemann","Andy Tennant","Jimmy Hayward","Terry George","Dean DeBlois","Francis Lawrence","Chris Wedge","Steve Martino","Jim Sheridan","Denis Villeneuve","Wai-keung Lau","Sean Penn","Wilson Yip","Shane Black","Cameron Crowe","Stanley Kramer","Mark Osborne","Jennifer Yuh","Curtis Hanson","Mathieu Kassovitz","Roberto Benigni","Terry Jones","Ang Lee","Luc Besson","Adam Elliot","Joon-ho Bong","John Woo","Dan Scanlon","Rob Letterman","Doug Liman","Joel Zwick","Steven Soderbergh","Chan-wook Park","Tim Johnson","Guillermo del Toro","Franklin J. Schaffner","Oliver Stone","Barry Levinson","George P. Cosmatos","Rupert Wyatt","Kevin Reynolds","John G. Avildsen","Keenen Ivory Wayans","Raja Gosnell","Michael Patrick King","Bibo Bergeron","Mike Mitchell","Frank Miller","Stanley Donen","Rupert Sanders","William Cottrell","Andrei Tarkovsky","Irvin Kershner","Richard Marquand","Joseph Kosinski","Nathan Greno","Chris Buck","Seth MacFarlane","Jonathan Mostow","François Truffaut","Marc Webb","Michel Hazanavicius","Joss Whedon","John Lee Hancock","Kirk De Micco","Michael Cimino","Julian Schnabel","David Lynch","William Friedkin","Andrew Davis","Clyde Bruckman","John Sturges","Tate Taylor","Gary Ross","Thomas Vinterberg","Robert Rossen","Olivier Nakache","Harald Zwart","Roger Allers","Florian Henckel von Donnersmarck","Peter Segal","Chris Renaud","John Frankenheimer","Charles Laughton","Anne Fletcher","Gabriele Muccino","Juan José Campanella","Jonathan Demme","David Silverman","Robert Wise","John Carpenter","Carol Reed","Peter Weir","David Slade","Chris Weitz","Frank Coraci","Sam Peckinpah","Bobby Farrelly","Kenneth Branagh","Krzysztof Kieslowski","Robert Mulligan","Lee Unkrich","Catherine Hardwicke","Jan de Bont","James McTeigue","Gavin O'Connor","David Dobkin","Nancy Meyers","Walt Becker","Rich Moore","Gavin Hood"};
	final static int [] DIRECTOR_FREQ_INT = {13,9,8,6,6,6,6,5,5,5,5,5,5,5,5,5,5,5,5,5,4,4,4,4,4,4,4,4,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1};




}
